<script setup lang="ts">
import { ref } from "vue";
import { onLoad, onPullDownRefresh } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import { pathApi, type PathDetail, type PathNode } from "../../../services/pathPlan";
const selectedId = ref(""), detail = ref<PathDetail | null>(null), loading = ref(false), busy = ref(""), error = ref(""), notice = ref("");
const labels: Record<string,string> = { intro: "导读", lesson: "章节", practice: "练习", homework: "小作业" };
async function load() { loading.value = true; error.value = ""; try { detail.value = await pathApi.detail("P5"); if (selectedId.value && !detail.value.nodes.some(node => node.id === selectedId.value)) notice.value = "该专题节点未在当前已发布路径中找到。"; } catch (e) { detail.value = null; error.value = e instanceof Error ? e.message : "专题暂不可用"; } finally { loading.value = false; } }
async function enter(node: PathNode) { if (node.status !== "available" || busy.value) return; busy.value = node.id; error.value = ""; try { const entry = await pathApi.enter("P5", node.id); if (entry.attemptId) uni.navigateTo({ url: `/pages/attempt/paper/index?id=${encodeURIComponent(entry.attemptId)}` }); else if (entry.type === "lesson" && entry.id) uni.navigateTo({ url: `/pages/learn/lesson/index?id=${encodeURIComponent(entry.id)}` }); else notice.value = "节点入口缺少可打开的课时或作答编号。"; } catch (e) { error.value = e instanceof Error ? e.message : "进入专题节点失败"; } finally { busy.value = ""; } }
onLoad(query => { selectedId.value = String(query?.id || ""); void load(); }); onPullDownRefresh(() => { void load().finally(() => uni.stopPullDownRefresh()); });
</script>
<template><view class="mobile-page"><MNavBar title="专题学习" back /><scroll-view scroll-y class="topic-scroll"><view class="page-scroll"><view class="hero"><text class="eyebrow">PATH 05 · TOPIC STUDY</text><text class="hero-title">{{ detail?.title || '专题学习' }}</text><text class="hero-copy">{{ detail?.description || '导读、章节、练习与作业由当前已发布路径决定。' }}</text><text v-if="detail?.progress != null" class="hero-progress">路径进度 {{ detail.progress }}%</text></view>
  <view v-if="loading" class="m-state">正在读取专题目录…</view><view v-if="error" class="m-state error">{{ error }}<button class="retry" @click="load">重试</button></view><view v-if="notice" class="m-state warning">{{ notice }}</view><view v-if="detail && !detail.nodes.length" class="m-state">当前暂无已发布专题节点。</view><view v-if="detail?.nodes.length" class="section-title">学习目录</view>
  <view v-for="(node,index) in detail?.nodes || []" :key="node.id" class="m-list-row" :class="{ selected: node.id === selectedId }" @click="enter(node)"><view class="serial">{{ String(index + 1).padStart(2,'0') }}</view><view class="body"><text class="title">{{ node.title }}</text><text class="meta">{{ labels[node.resourceType] || node.resourceType || '学习节点' }} · {{ node.status === 'done' ? '已完成' : node.status === 'available' ? '可进入' : node.status === 'locked' ? '未解锁' : '状态待确认' }}</text><text v-if="node.status === 'locked' && node.lockReason" class="meta">{{ node.lockReason }}</text></view><text class="chevron">{{ busy === node.id ? '…' : '›' }}</text></view>
  </view></scroll-view></view></template>
<style scoped>.topic-scroll{height:calc(100vh - 92rpx)}.hero{padding:34rpx;border-radius:33rpx;background:linear-gradient(140deg,#502851,#a44877);color:#fff}.hero .eyebrow{color:#ffbdd6}.hero-title{display:block;font-size:41rpx;font-weight:850}.hero-copy{display:block;margin-top:14rpx;color:#ffe4ee;font-size:24rpx;line-height:1.6}.hero-progress{display:block;margin-top:23rpx;font-size:24rpx;font-weight:750}.serial{display:flex;align-items:center;justify-content:center;width:65rpx;height:65rpx;border-radius:19rpx;background:#fcecf4;color:#ac4c78;font-size:22rpx;font-weight:800}.selected{border-color:#cf82ad}.retry{display:block;margin-top:12rpx;background:transparent;color:#9e2d44;text-align:left;font-size:23rpx}</style>
