import { obj, str, num } from "../attempt/attemptModel";
export type Course={id:string;title:string;description:string;progress:number|null};
export type LessonItem={id:string;title:string;status:"locked"|"completed"|"current"|"available"|"unknown";duration:string};
export type Chapter={id:string;title:string;lessons:LessonItem[]};
const positive=(x:unknown):string|null=>{const s=str(x);return /^[1-9]\d*$/.test(s)&&Number.isSafeInteger(Number(s))?s:null;};
export function courseOf(raw:unknown):Course|null{const x=obj(raw),id=positive(x.id),title=str(x.title);if(!id||!title)return null;const progress=num(x.progressPercent??x.progress);return {id,title,description:str(x.description),progress:progress!==null&&progress>=0&&progress<=100?progress:null};}
export function chaptersOf(raw:unknown):Chapter[]|null{const x=obj(raw),list=Array.isArray(raw)?raw:Array.isArray(x.chapters)?x.chapters:null;if(!list)return null;const chapters=list.map((v):Chapter|null=>{const c=obj(v),id=positive(c.id),title=str(c.title??c.name),lessonsRaw=Array.isArray(c.lessons)?c.lessons:[];if(!id||!title)return null;const lessons=lessonsRaw.map((v):LessonItem|null=>{const l=obj(v),lid=positive(l.id),lt=str(l.title??l.name);if(!lid||!lt)return null;const status=str(l.status).toLowerCase();return {id:lid,title:lt,status:status==="locked"||l.locked===true?"locked":status==="completed"||l.completed===true?"completed":status==="current"?"current":status==="available"||l.locked===false?"available":"unknown",duration:str(l.duration)};});return lessons.some(v=>v===null)?null:{id,title,lessons:lessons as LessonItem[]};});return chapters.some(v=>v===null)?null:chapters as Chapter[];}
export type Lesson={title:string;content:string;videoUrl:string;completionPolicy:"practice_required"|"read_only"|null;practiceRef:string|null;readCompleted:boolean|null;lessonCompleted:boolean|null;practicePassed:boolean|null};
export function lessonOf(raw:unknown):Lesson|null{const x=obj(raw),title=str(x.title),content=str(x.content);if(!title||!content)return null;const policy=x.completion_policy==="read_only"||x.completionPolicy==="read_only"?"read_only":x.completion_policy==="practice_required"||x.completionPolicy==="practice_required"?"practice_required":null;const url=str(x.video_url??x.videoUrl);return {title,content,videoUrl:/^https:\/\//i.test(url)?url:"",completionPolicy:policy,practiceRef:positive(x.practiceId??x.practiceRef),readCompleted:typeof x.readCompleted==="boolean"?x.readCompleted:null,lessonCompleted:typeof x.lessonCompleted==="boolean"?x.lessonCompleted:null,practicePassed:typeof x.practicePassed==="boolean"?x.practicePassed:null};}
export type ReadingBlock={kind:"heading"|"paragraph"|"list"|"quote"|"code"|"math"|"image";text:string;level?:number;src?:string};
/** Native text blocks: Markdown is never converted into executable HTML. */
export function readingBlocks(markdown:string):ReadingBlock[]{const out:ReadingBlock[]=[];let code=false,math=false,buffer:string[]=[];const flush=(kind:ReadingBlock["kind"])=>{if(buffer.length){out.push({kind,text:buffer.join("\n")});buffer=[];}};
  for(const line of markdown.replace(/\r\n/g,"\n").split("\n")){const trimmed=line.trim();
    if(trimmed.startsWith("```")){if(code){flush("code");code=false;}else{flush("paragraph");code=true;}continue;}
    if(code){buffer.push(line);continue;}
    if(trimmed==="$$"){if(math){flush("math");math=false;}else{flush("paragraph");math=true;}continue;}
    if(math){buffer.push(line);continue;}
    if(!trimmed){flush("paragraph");continue;}
    const image=/^!\[([^\]]*)\]\((https:\/\/[^\s)]+)\)$/.exec(trimmed);if(image){flush("paragraph");out.push({kind:"image",text:image[1],src:image[2]});continue;}
    const heading=/^(#{1,4})\s+(.+)$/.exec(trimmed);if(heading){flush("paragraph");out.push({kind:"heading",text:heading[2],level:heading[1].length});continue;}
    const list=/^[-*]\s+(.+)$/.exec(trimmed);if(list){flush("paragraph");out.push({kind:"list",text:list[1]});continue;}
    const quote=/^>\s?(.+)$/.exec(trimmed);if(quote){flush("paragraph");out.push({kind:"quote",text:quote[1]});continue;}
    buffer.push(line);
  }
  flush(code?"code":math?"math":"paragraph");return out;}
export type ReadReceipt={readCompleted:boolean;lessonCompleted:boolean;practicePassed:boolean};
export function readReceipt(raw:unknown):ReadReceipt|null{const x=obj(raw);if(typeof x.readCompleted!=="boolean"||typeof x.lessonCompleted!=="boolean"||typeof x.practicePassed!=="boolean"||x.lessonCompleted&&!x.readCompleted)return null;return {readCompleted:x.readCompleted,lessonCompleted:x.lessonCompleted,practicePassed:x.practicePassed};}
export type GraphNode={id:number;name:string;description:string;locked:boolean|null;preparing:boolean|null;score:number|null;insufficientSample:boolean|null;domain:string};
export function nodeOf(raw:unknown):GraphNode|null{const x=obj(raw),id=num(x.id),name=str(x.name);if(!id||!Number.isSafeInteger(id)||!name)return null;const score=num(x.score);return {id,name,description:str(x.description),locked:typeof x.locked==="boolean"?x.locked:null,preparing:typeof x.preparing==="boolean"?x.preparing:null,score:score!==null&&score>=0&&score<=100?score:null,insufficientSample:typeof x.insufficientSample==="boolean"?x.insufficientSample:null,domain:str(x.domainName??x.domain)};}
export function graphOf(raw:unknown):GraphNode[]|null{const x=obj(raw);if(!Array.isArray(x.nodes)||!Array.isArray(x.edges))return null;const mapped=x.nodes.map(nodeOf);return mapped.some(v=>v===null)?null:mapped as GraphNode[];}
export function nodeStatus(n:GraphNode):string{return n.preparing===true?"内容筹备中":n.locked===true?"前置锁定":n.locked===null||n.preparing===null||n.insufficientSample===null?"证据待核实":n.insufficientSample===true?"样本不足":n.score===null?"尚未测量":n.score>=80?"已掌握":"待巩固";}
export type CardKey="origin"|"prototype"|"capability"|"ladder";
export const cardTabs:readonly {key:CardKey;label:string}[]=[{key:"origin",label:"起源"},{key:"prototype",label:"现实原型"},{key:"capability",label:"能力地图"},{key:"ladder",label:"抽象阶梯"}];
export type Narrative={version:number;cards:Record<CardKey,string>;missing:string[]};
export function narrativeOf(raw:unknown):Narrative|null{const x=obj(raw),version=num(x.publishedVersion);if(!version||!Number.isSafeInteger(version)||!x.published_snapshot||typeof x.published_snapshot!=="object"||Array.isArray(x.published_snapshot))return null;const s=obj(x.published_snapshot);const cards={origin:str(s.origin),prototype:str(s.prototype),capability:str(s.capability),ladder:str(s.ladder)};return {version,cards,missing:cardTabs.filter(t=>!cards[t.key]).map(t=>t.label)};}
export type Pred={stem:string;options:string[];mode:1|2|3|4};
export type Step={id:number;seq:number;content:string;warrant:string;motive:string;offRamp:string;warrantNodes:number[];prediction:Pred|null};
export type Chain={id:number;title:string;quality:number|null;view:number|null;summary:string;chainVersion:number|null;steps:Step[]};
export function chainsOf(raw:unknown):Chain[]|null{if(!Array.isArray(raw))return null;const list=raw.map((v):Chain|null=>{const p=obj(v),id=num(p.id),title=str(p.title),version=num(p.chainVersion);if(!id||!title||!Array.isArray(p.steps))return null;const steps=p.steps.map((s):Step|null=>{const q=obj(s),sid=num(q.id),seq=num(q.seq),content=str(q.content),pr=obj(q.prediction),pm=num(pr.mode);if(!sid||!seq||!content)return null;const pred:Pred|null=(pm===1||pm===2||pm===3||pm===4)&&str(pr.stem)?{stem:str(pr.stem),mode:pm,options:Array.isArray(pr.options)?pr.options.map(str).filter(Boolean):[]}:null;return {id:sid,seq,content,warrant:str(q.warrant),motive:str(q.motive),offRamp:str(q.off_ramp),warrantNodes:(Array.isArray(q.warrant_nodes)?q.warrant_nodes:[]).map(num).filter((n):n is number=>n!==null),prediction:pred};});return steps.some(x=>x===null)?null:{id,title,quality:num(p.quality),view:num(p.view),summary:str(p.summary),chainVersion:version,steps:(steps as Step[]).sort((a,b)=>a.seq-b.seq)};});return list.some(v=>v===null)?null:list as Chain[];}
