<script setup lang="ts">
import { computed, ref } from "vue";
import { onLoad, onShow } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import MSheet from "../../../components/MSheet.vue";
import { currentMobileUserId } from "../../../services/mobileClient";
import { learnApi } from "../../../services/learnApi";
import { chainsOf, type Chain, type Step } from "../../../features/learn/learnModel";
type Mode="read"|"predict"|"dual"|"multi"|"ai";
const modes:{key:Mode;label:string}[]=[{key:"read",label:"通读"},{key:"predict",label:"预测"},{key:"dual",label:"顺逆"},{key:"multi",label:"多解"},{key:"ai",label:"AI"}];
const type=ref("question"),id=ref("");const mode=ref<Mode>("read");const chains=ref<Chain[]>([]);const loading=ref(true);const error=ref("");const selectedPath=ref<number|null>(null);const selectedStep=ref<number|null>(null);const selectedOption=ref<number|null>(null);const written=ref("");const feedback=ref("");const breakNote=ref("");const busy=ref(false);const sheet=ref(false);const kind=ref("未指定");
const path=computed(()=>chains.value.find(p=>p.id===selectedPath.value)||chains.value[0]||null);const step=computed(()=>path.value?.steps.find(s=>s.id===selectedStep.value)||path.value?.steps[0]||null);
const forward=computed(()=>chains.value.find(p=>p.view===1)||null);const backward=computed(()=>chains.value.find(p=>p.view===2)||null);
const policy=ref<{state?:string;assistancePolicy?:string;capabilities?:Record<string,unknown>}|null>(null);
let shownOnce=false;
function refreshPolicy(){const user=currentMobileUserId();if(!user){policy.value=null;return;}try{const x=uni.getStorageSync(`lm.mobile.activeAttempt:${user}`);policy.value=x&&typeof x==="object"?x as {state?:string;assistancePolicy?:string;capabilities?:Record<string,unknown>}:null;}catch{policy.value=null;}}
const blocked=computed(()=>{const p=policy.value;if(!p||p.state!=="in_progress")return false;if(p.assistancePolicy==="learning")return false;return !(p.assistancePolicy==="open_book"&&type.value==="formula");});
const aiAllowed=computed(()=>type.value==="question"&&(!policy.value||policy.value.state!=="in_progress"||policy.value.assistancePolicy==="learning"&&policy.value.capabilities?.ai===true));
function queryMode():"read"|"predict"|"compare"{return mode.value==="predict"?"predict":mode.value==="dual"||mode.value==="multi"?"compare":"read";}
function choosePath(p:Chain){selectedPath.value=p.id;selectedStep.value=p.steps[0]?.id||null;selectedOption.value=null;written.value="";feedback.value="";breakNote.value="";}
function chooseStep(s:Step){selectedStep.value=s.id;selectedOption.value=null;written.value="";feedback.value="";breakNote.value="";sheet.value=true;}
async function load(){loading.value=true;error.value="";chains.value=[];if(blocked.value){error.value="当前作答策略暂不允许查看该深钻内容。交卷后再试。";loading.value=false;return;}try{const mapped=chainsOf(await learnApi.deepdive(type.value,id.value,queryMode()));if(!mapped)throw new Error("解法链字段尚未对齐");chains.value=mapped;if(mapped[0])choosePath(mapped[0]);}catch(e){error.value=e instanceof Error?e.message:"深钻暂不可用";}finally{loading.value=false;}}
function changeMode(next:Mode){if(mode.value===next)return;mode.value=next;feedback.value="";if(next!=="ai")void load();}
async function predict(){const p=path.value,s=step.value,pr=s?.prediction;if(!p?.chainVersion||!s||!pr||busy.value)return;const answer=pr.mode<=2?(selectedOption.value===null?"":pr.options[selectedOption.value]||""):written.value.trim();if(!answer)return;busy.value=true;feedback.value="";try{const r=await learnApi.predict(type.value,id.value,{solutionPathId:p.id,chainVersion:p.chainVersion,stepId:s.id,answer,requestId:`${Date.now()}-${Math.random().toString(36).slice(2)}`});feedback.value=typeof r==="string"&&r.trim()?r:"服务端已处理预测，但尚无可显示的点评字段；不在本机判对。";}catch(e){feedback.value="预测未确认："+(e instanceof Error?e.message:"请求失败");}finally{busy.value=false;}}
async function reportBreak(){const p=path.value,s=step.value;if(!p?.chainVersion||!s||busy.value)return;busy.value=true;breakNote.value="";try{const r=await learnApi.reportBreak(type.value,id.value,{solutionPathId:p.id,chainVersion:p.chainVersion,stepId:s.id,kind:kind.value,requestId:`${Date.now()}-${Math.random().toString(36).slice(2)}`});breakNote.value=r===null||r===undefined?"接口未返回可核实回执，请稍后到错题本确认。":"服务端已接收自报；自报与客观观察分开记录。";}catch(e){breakNote.value="自报未确认："+(e instanceof Error?e.message:"请求失败");}finally{busy.value=false;}}
function toAi(){if(!aiAllowed.value)return;uni.navigateTo({url:`/pages/social/ai/index?questionId=${encodeURIComponent(id.value)}`});}
function inputValue(event:unknown):string{const e=event as {detail?:{value?:unknown}};return typeof e?.detail?.value==="string"?e.detail.value:"";}
onLoad(q=>{type.value=String(q?.type||"question");id.value=String(q?.id||"");if(type.value!=="question"&&type.value!=="formula"){error.value="深钻资源类型无效";loading.value=false;return;}refreshPolicy();void load();});
onShow(()=>{if(!shownOnce){shownOnce=true;return;}refreshPolicy();if(blocked.value){chains.value=[];error.value="当前作答策略暂不允许查看该深钻内容。交卷后再试。";}else if(id.value)void load();});
</script>
<template><view class="mobile-page"><MNavBar title="推理链深钻" back/><scroll-view scroll-y class="screen"><view class="page-scroll"><view class="head"><text class="eyebrow">REASONING STUDIO</text><text class="page-title">看见每一步为什么成立</text><text class="muted">{{type==='formula'?'公式':'题目'}} #{{id}} · 内容按当前作答策略开放</text></view><view class="modes"><button v-for="m in modes" :key="m.key" :class="{active:mode===m.key}" @click="changeMode(m.key)">{{m.label}}</button></view>
  <view v-if="mode==='ai'" class="m-card ai"><text class="m-card-title">沿着这条思路继续追问</text><text class="muted">AI 回答由服务端权限和流式服务决定，不充当正确率或断链客观证据。</text><button class="m-button" :disabled="!aiAllowed" @click="toAi">{{aiAllowed?'进入 AI 答疑':'当前作答策略暂不开放 AI'}}</button></view>
  <template v-else><view v-if="loading" class="m-state">正在读取已开放的解法链…</view><view v-else-if="error" class="m-state error">{{error}}<button class="retry" @click="load">重试</button></view><view v-else-if="!chains.length" class="m-state">当前没有可展示的已发布解法链。</view><template v-else><scroll-view scroll-x class="path-tabs"><view class="path-inner"><button v-for="p in chains" :key="p.id" :class="{active:path?.id===p.id}" @click="choosePath(p)">{{p.title}}{{p.quality===2?' · AI 整理':''}}</button></view></scroll-view>
    <view v-if="mode==='read'" class="step-list"><button v-for="s in path?.steps||[]" :key="s.id" class="m-card step" @click="chooseStep(s)"><text class="step-no">{{String(s.seq).padStart(2,'0')}}</text><view><text class="step-content">{{s.content}}</text><text class="muted">点击看依据、动机与岔路 →</text></view></button></view>
    <view v-else-if="mode==='predict'" class="m-card"><text class="m-card-title">预测下一步</text><view class="step-picker"><button v-for="s in path?.steps||[]" :key="s.id" :class="{active:step?.id===s.id}" @click="selectedStep=s.id;selectedOption=null;written='';feedback=''">{{s.seq}}</button></view><view v-if="!step?.prediction" class="m-state">这一步没有已发布预测题。</view><template v-else><text class="prompt">{{step.prediction.stem}}</text><view v-if="step.prediction.mode<=2" class="pred-options"><button v-for="(o,i) in step.prediction.options" :key="i" :class="{active:selectedOption===i}" @click="selectedOption=i">{{o}}</button></view><textarea v-else class="written" :value="written" placeholder="写出你的预测，再与服务端点评对照" @input="written=inputValue($event)"/><button class="m-button" :disabled="busy||step.prediction.mode<=2&&selectedOption===null||step.prediction.mode>2&&!written.trim()" @click="predict">{{busy?'提交中…':'提交预测'}}</button><view v-if="feedback" class="m-state">{{feedback}}</view><text v-if="step.prediction.mode>=3" class="muted">简答预测只做对照和自报，不自动标成客观答对。</text></template></view>
    <view v-else-if="mode==='dual'" class="dual"><view v-for="(p,label) in [{name:'顺向 · 综合法',data:forward},{name:'逆向 · 分析法',data:backward}]" :key="label" class="m-card"><text class="m-card-title">{{p.name}}</text><view v-if="!p.data" class="m-state">暂无此方向的已发布解法。</view><view v-for="s in p.data?.steps||[]" :key="s.id" class="dual-step"><text>{{s.seq}}</text><text>{{s.content}}</text></view></view></view>
    <view v-else-if="mode==='multi'" class="multi"><view v-for="p in chains" :key="p.id" class="m-card"><text class="m-card-title">{{p.title}}</text><text class="muted">{{p.summary||'本解法暂无摘要'}} · {{p.steps.length}} 步</text><view v-for="s in p.steps" :key="s.id" class="multi-step">{{s.seq}} · {{s.content}}</view></view></view>
    <view v-if="mode==='read'&&path?.steps.length" class="m-card"><text class="m-card-title">哪里卡住了？</text><text class="muted">自报是一份个人学习证据，不等于客观预测观察。</text><view class="step-picker"><button v-for="s in path.steps" :key="s.id" :class="{active:step?.id===s.id}" @click="selectedStep=s.id">{{s.seq}}</button></view><view class="kind"><button v-for="k in ['依据','动机','岔路','未确定']" :key="k" :class="{active:kind===k}" @click="kind=k">{{k}}</button></view><button class="m-button secondary" :disabled="busy||!path.chainVersion||!step" @click="reportBreak">记录自报断点</button><text v-if="breakNote" class="muted">{{breakNote}}</text></view>
  </template></template></view></scroll-view><MSheet v-model="sheet" title="这一步为什么成立" height="medium"><view v-if="step" class="sheet-details"><text class="m-card-title">{{step.content}}</text><text>依据：{{step.warrant||'待补全'}}</text><text>动机：{{step.motive||'待补全'}}</text><text>岔路：{{step.offRamp||'待补全'}}</text><text v-if="step.warrantNodes.length">关联知识点：{{step.warrantNodes.join('、')}}</text></view></MSheet></view></template>
<style scoped>.screen{height:calc(100vh - 92rpx)}.head{display:flex;flex-direction:column;gap:11rpx;margin:8rpx 0 28rpx}.modes{display:flex;gap:7rpx;margin-bottom:24rpx}.modes button{flex:1;min-height:73rpx;padding:8rpx;border-radius:15rpx;background:#eaf0f9;color:#56708e;font-size:23rpx}.modes button.active{background:#2f5fd7;color:white;font-weight:800}.path-tabs{white-space:nowrap;margin-bottom:16rpx}.path-inner{display:flex;gap:11rpx}.path-inner button{flex:none;padding:14rpx 23rpx;border:1rpx solid #d5e0f1;border-radius:99rpx;background:white;color:#486287;font-size:23rpx}.path-inner button.active{background:#eaf1ff;border-color:#4d78df;color:#2354c5}.step{display:flex;gap:19rpx;align-items:flex-start;width:100%;text-align:left;color:#263b59}.step-no{font-size:31rpx;color:#2f61d5;font-weight:850}.step-content{display:block;margin-bottom:12rpx;font-size:27rpx;line-height:1.65}.step-picker,.kind{display:flex;flex-wrap:wrap;gap:10rpx;margin:23rpx 0}.step-picker button,.kind button{min-width:64rpx;padding:12rpx;border-radius:13rpx;background:#eef3fa;color:#536b8e;font-size:23rpx}.step-picker button.active,.kind button.active{background:#315ed2;color:white}.prompt{display:block;white-space:pre-wrap;font-size:27rpx;font-weight:750;line-height:1.6;margin:22rpx 0}.pred-options{display:flex;flex-direction:column;gap:10rpx;margin-bottom:20rpx}.pred-options button{padding:19rpx;border:1rpx solid #dbe4f0;border-radius:15rpx;background:#fafcff;color:#304968;text-align:left;font-size:24rpx}.pred-options button.active{border-color:#4e78e4;background:#ecf2ff}.written{width:100%;min-height:200rpx;padding:17rpx;border:1rpx solid #dbe4f0;border-radius:14rpx;margin-bottom:16rpx}.dual-step,.multi-step{padding:18rpx 0;border-top:1rpx solid #e8edf5;color:#354e70;font-size:24rpx;line-height:1.6}.dual-step{display:flex;gap:18rpx}.dual-step text:first-child{color:#2f62d6;font-weight:800}.sheet-details{display:flex;flex-direction:column;gap:25rpx;color:#344b6b;font-size:25rpx;line-height:1.6}.ai .m-button{margin-top:26rpx}.retry{margin-top:15rpx;color:#2455ce;background:#eef3ff}</style>
