<script setup lang="ts">
import { computed, ref } from "vue";
import { onPullDownRefresh, onShow } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import MSheet from "../../../components/MSheet.vue";
import { pathApi, type PathDetail, type PathNode } from "../../../services/pathPlan";
const detail = ref<PathDetail | null>(null), picked = ref<PathNode | null>(null), loading = ref(false), busy = ref(false), error = ref(""), notice = ref("");
const mapNodes = computed(() => { const nodes = [...(detail.value?.nodes ?? [])]; return nodes.every(node => node.y !== null) ? nodes.sort((a,b) => (a.y ?? 0)-(b.y ?? 0)) : nodes; });
const placement = (node: PathNode) => node.x === null ? "center" : node.x < 45 ? "left" : node.x > 55 ? "right" : "center";
async function load() { loading.value = true; error.value = ""; try { detail.value = await pathApi.map("P6"); } catch (e) { detail.value = null; error.value = e instanceof Error ? e.message : "关卡暂不可用"; } finally { loading.value = false; } }
async function enter() { if (!picked.value || picked.value.status !== "available" || busy.value) return; busy.value = true; error.value = ""; try { const entry = await pathApi.enter("P6", picked.value.id); picked.value = null; if (entry.attemptId) uni.navigateTo({ url: `/pages/attempt/paper/index?id=${encodeURIComponent(entry.attemptId)}` }); else if (entry.type === "lesson" && entry.id) uni.navigateTo({ url: `/pages/learn/lesson/index?id=${encodeURIComponent(entry.id)}` }); else notice.value = "节点已进入，但服务端未返回可打开的课时或作答编号。"; } catch (e) { error.value = e instanceof Error ? e.message : "进入关卡失败"; } finally { busy.value = false; } }
onShow(() => { void load(); }); onPullDownRefresh(() => { void load().finally(() => uni.stopPullDownRefresh()); });
</script>
<template><view class="mobile-page adventure"><MNavBar title="冒险闯关" back /><scroll-view scroll-y class="scroll"><view class="page-scroll"><view class="hero"><text class="eyebrow">PATH 06 · ADVENTURE</text><text class="hero-title">沿着自己的地图前进</text><text class="hero-copy">星级、Boss 和锁定原因来自你的关卡记录。</text><view class="hero-meta"><text>{{ detail?.rank || '段位待确认' }}</text><text>{{ detail?.progress == null ? '进度待确认' : `进度 ${detail.progress}%` }}</text></view></view>
  <view v-if="loading" class="m-state">正在展开地图…</view><view v-if="error" class="m-state error">{{ error }}<button class="retry" @click="load">重试</button></view><view v-if="detail && !detail.nodes.length" class="m-state">地图暂无已发布关卡。</view>
  <view v-if="detail?.nodes.length" class="route"><view v-for="node in mapNodes" :key="node.id" class="route-row" :class="placement(node)"><view class="rail" /><button class="node" :class="[node.status,node.isBoss ? 'boss' : '']" @click="picked = node"><text class="node-mark">{{ node.isBoss ? '◆' : node.status === 'done' ? '★' : node.status === 'locked' ? '♢' : '→' }}</text><text class="node-title">{{ node.title }}</text><text class="node-meta">{{ node.stars === null ? node.status === 'locked' ? '尚未解锁' : '星级待确认' : `${node.stars} 星` }}</text></button></view><text v-if="mapNodes.some(node => node.x===null || node.y===null)" class="map-note">部分关卡缺少地图坐标，已按服务端返回顺序排列。</text></view>
  <view v-if="notice" class="m-state warning">{{ notice }}</view></view></scroll-view><MSheet :model-value="!!picked" :title="picked?.title || '关卡'" height="compact" @update:model-value="picked = null"><view v-if="picked" class="sheet-body"><text class="m-chip">{{ picked.isBoss ? 'BOSS 关' : '普通关卡' }}</text><text>{{ picked.status === 'available' ? '可以挑战' : picked.status === 'done' ? '已完成' : picked.status === 'locked' ? '尚未解锁' : '状态待确认' }}</text><text class="muted">{{ picked.lockReason || picked.description || '解锁要求由服务端判定。' }}</text></view><template #footer><button class="m-button" :disabled="picked?.status !== 'available' || busy" @click="enter">{{ busy ? '正在进入…' : '进入关卡' }}</button></template></MSheet></view></template>
<style scoped>.adventure{display:flex;flex-direction:column;height:100vh}.scroll{flex:1;min-height:0}.hero{padding:36rpx;border-radius:34rpx;background:linear-gradient(145deg,#152a46,#225a6e);color:white}.hero .eyebrow{color:#9fe2dd}.hero-title{display:block;font-size:39rpx;font-weight:850}.hero-copy{display:block;margin-top:14rpx;color:#d7eeef;font-size:24rpx;line-height:1.55}.hero-meta{display:flex;gap:12rpx;margin-top:24rpx}.hero-meta text{padding:9rpx 16rpx;border-radius:99rpx;background:#ffffff20;font-size:22rpx}.route{position:relative;margin:28rpx 0}.route-row{position:relative;display:flex;min-height:168rpx;align-items:center}.route-row.right{justify-content:flex-end}.route-row.center{justify-content:center}.rail{position:absolute;left:50%;top:0;bottom:0;width:4rpx;background:#cbdedc}.node{position:relative;z-index:1;display:flex;flex-direction:column;align-items:flex-start;justify-content:center;width:45%;min-height:135rpx;padding:17rpx 20rpx;border:2rpx solid #c8e5de;border-radius:26rpx;background:#fff;color:#214e57;text-align:left;box-shadow:0 9rpx 25rpx #315c5b17}.node.done{background:#eaf9f0;border-color:#a8dbbe}.node.available{border-color:#5aa9a0;box-shadow:0 0 0 5rpx #6bb9ac22}.node.locked{background:#f0f2f5;border-color:#dce3e9;color:#748394}.node.boss{border-color:#c5a76d;background:#fff8ea}.node-mark{font-size:28rpx}.node-title{font-size:24rpx;font-weight:800}.node-meta{margin-top:6rpx;font-size:20rpx}.map-note{display:block;margin-top:15rpx;color:#71839a;font-size:20rpx}.sheet-body{display:flex;flex-direction:column;align-items:flex-start;gap:16rpx}.retry{display:block;margin-top:12rpx;background:transparent;color:#9e2d44;text-align:left;font-size:23rpx}</style>
