<script setup lang="ts">
import { ref } from "vue";
import { onLoad, onPullDownRefresh } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import MSheet from "../../../components/MSheet.vue";
import { assessmentApi, planApi, type AssessmentReport } from "../../../services/pathPlan";
const id = ref(""), report = ref<AssessmentReport | null>(null), loading = ref(false), error = ref(""), notice = ref(""), showPlan = ref(false), busy = ref(false), dailyMinutes = ref(20), goal = ref("");
async function load() { if (!id.value) { error.value = "缺少测评记录编号，无法读取报告。"; return; } loading.value = true; error.value = ""; try { report.value = await assessmentApi.report(id.value); } catch (e) { report.value = null; error.value = e instanceof Error ? e.message : "测评报告暂不可用"; } finally { loading.value = false; } }
async function createPlan() { if (!report.value || busy.value) return; busy.value = true; error.value = ""; try { await planApi.create(goal.value, dailyMinutes.value); const plan = await planApi.current(); if (!plan) throw new Error("计划生成请求已发送，但尚未读到服务端计划，请稍后在计划页刷新。"); showPlan.value = false; uni.navigateTo({ url: "/pages/plan/index" }); } catch (e) { error.value = e instanceof Error ? e.message : "计划未确认"; notice.value = "如请求已发出，请先到计划页核对，避免重复生成。"; } finally { busy.value = false; } }
onLoad(query => { id.value = String(query?.id || query?.recordId || ""); void load(); }); onPullDownRefresh(() => { void load().finally(() => uni.stopPullDownRefresh()); });
</script>
<template><view class="mobile-page report"><MNavBar title="测评报告" back /><scroll-view scroll-y class="scroll"><view class="page-scroll"><view class="hero"><text class="eyebrow">ASSESSMENT REPORT</text><text class="hero-title">从这里，开始下一步</text><text class="hero-copy">报告展示服务端定级与维度，不根据答题数本地推算。</text></view>
  <view v-if="loading" class="m-state">正在读取报告…</view><view v-if="error" class="m-state error">{{ error }}<button class="retry" @click="load">重试</button></view><view v-if="notice" class="m-state warning">{{ notice }}</view>
  <template v-if="report"><view class="level-card"><text class="level-label">当前位置</text><text class="level-value">{{ report.level ? /^L/i.test(report.level) ? report.level : `L${report.level}` : '定级待确认' }}</text><text class="level-status">{{ report.status || '状态待确认' }}</text></view><view class="section-title">能力维度</view><view v-if="!report.dimensions.length" class="m-state">维度画像暂未由服务端返回。</view><view v-for="dim in report.dimensions" :key="dim.name" class="dimension"><view class="dimension-top"><text>{{ dim.name }}</text><text>{{ dim.percent === null ? '待确认' : `${dim.percent}%` }}</text></view><view class="track"><view :style="{ width: `${Math.max(0,Math.min(100,dim.percent ?? 0))}%` }" /></view></view>
    <view class="m-card start-card"><text class="m-card-title">推荐起点</text><text class="start-value">{{ report.recommendedStart || '服务端尚未给出推荐起点' }}</text><text class="muted">计划生成会把推荐起点与每日可投入时间一起交给服务端处理。</text></view><button class="m-button" @click="showPlan = true">生成学习计划</button></template>
  </view></scroll-view><MSheet v-model="showPlan" title="确认学习计划" height="compact"><view class="plan-form"><text class="m-field-label">本阶段目标</text><input v-model="goal" class="m-input" placeholder="例如：巩固本次测评薄弱点" :maxlength="80" /><text class="m-field-label">每日学习时长</text><slider :value="dailyMinutes" :min="10" :max="120" :step="5" show-value active-color="#5d68d5" @change="dailyMinutes = $event.detail.value" /><text class="muted">规则计划由服务端生成；未确认成功前不会显示已制定。</text></view><template #footer><button class="m-button" :disabled="busy || !goal.trim()" @click="createPlan">{{ busy ? '生成中…' : '确认生成' }}</button></template></MSheet></view></template>
<style scoped>.report{display:flex;flex-direction:column;height:100vh}.scroll{flex:1;min-height:0}.hero{padding:35rpx;border-radius:33rpx;background:linear-gradient(145deg,#242e5e,#656bb1);color:#fff}.hero .eyebrow{color:#c7d0ff}.hero-title{display:block;font-size:40rpx;font-weight:850}.hero-copy{display:block;margin-top:12rpx;color:#e0e5ff;font-size:23rpx;line-height:1.6}.level-card{display:flex;align-items:center;gap:20rpx;margin:22rpx 0;padding:29rpx;border:1rpx solid #dbe2fb;border-radius:28rpx;background:#fff}.level-label{color:#526584;font-size:23rpx}.level-value{flex:1;color:#3f4eaa;font-size:56rpx;font-weight:900}.level-status{color:#697995;font-size:22rpx}.dimension{margin-bottom:25rpx;padding:21rpx 25rpx;border-radius:22rpx;background:#fff}.dimension-top{display:flex;justify-content:space-between;font-size:24rpx;font-weight:700}.track{height:10rpx;margin-top:16rpx;border-radius:99rpx;background:#e9edf7}.track view{height:100%;border-radius:99rpx;background:#6b7ff1}.start-card{margin-top:34rpx}.start-value{display:block;margin:17rpx 0;color:#303f82;font-size:28rpx;font-weight:800}.plan-form .muted{display:block;margin-top:18rpx}.retry{display:block;margin-top:12rpx;background:transparent;color:#9e2d44;text-align:left;font-size:23rpx}</style>
