<script setup lang="ts">
import { ref } from "vue";
import { onLoad } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import { learnApi } from "../../../services/learnApi";
import { chaptersOf, courseOf, type Chapter, type Course, type LessonItem } from "../../../features/learn/learnModel";
const id=ref("");const course=ref<Course|null>(null);const chapters=ref<Chapter[]>([]);const expanded=ref<string[]>([]);const loading=ref(true);const error=ref("");
async function load(){loading.value=true;error.value="";try{const [detail,tree]=await Promise.all([learnApi.course(id.value),learnApi.tree(id.value)]);const mapped=courseOf(detail),items=chaptersOf(tree);if(!mapped||!items)throw new Error("课程详情或章节树字段尚未对齐");course.value=mapped;chapters.value=items;expanded.value=items.map(x=>x.id);}catch(e){course.value=null;error.value=e instanceof Error?e.message:"课程暂不可用";}finally{loading.value=false;}}
function toggle(id:string){expanded.value=expanded.value.includes(id)?expanded.value.filter(x=>x!==id):[...expanded.value,id];}
function open(item:LessonItem){if(item.status==="locked"||item.status==="unknown")return;uni.navigateTo({url:`/pages/learn/lesson/index?id=${item.id}&courseId=${id.value}`});}
onLoad(q=>{id.value=String(q?.id||"");void load();});
</script>
<template><view class="mobile-page"><MNavBar title="课程详情" back/><scroll-view scroll-y class="screen"><view class="page-scroll"><view v-if="loading" class="m-state">正在读取课程与章节…</view><view v-else-if="!course" class="m-state error">{{error||'课程暂不可用'}}<button class="retry" @click="load">重试</button></view><template v-else><view class="hero"><text class="eyebrow">STRUCTURED LEARNING · 系统课程</text><text class="hero-title">{{course.title}}</text><text class="hero-desc">{{course.description||'按章节循序学习，每一课的完成条件由服务端确认。'}}</text><view class="progress"><text>学习进度</text><text>{{course.progress===null?'待服务端确认':course.progress+'%'}}</text></view><view class="bar"><view :style="{width:(course.progress??0)+'%'}" /></view></view>
  <view class="section-title">章节目录 <text class="muted">{{chapters.length}} 章</text></view><view v-if="!chapters.length" class="m-state">课程尚无已发布课时。</view><view v-for="(chapter,i) in chapters" :key="chapter.id" class="m-card chapter"><button class="chapter-head" @click="toggle(chapter.id)"><text class="chapter-no">{{String(i+1).padStart(2,'0')}}</text><text class="chapter-title">{{chapter.title}}</text><text>{{expanded.includes(chapter.id)?'⌃':'⌄'}}</text></button><view v-if="expanded.includes(chapter.id)"><view v-if="!chapter.lessons.length" class="empty">本章暂无可读课时</view><button v-for="lesson in chapter.lessons" :key="lesson.id" class="lesson" :disabled="lesson.status==='locked'||lesson.status==='unknown'" @click="open(lesson)"><text class="state-dot" :class="lesson.status">{{lesson.status==='completed'?'✓':lesson.status==='locked'?'锁':'•'}}</text><view class="body"><text class="title">{{lesson.title}}</text><text class="meta">{{lesson.status==='completed'?'已完成':lesson.status==='current'?'正在学习':lesson.status==='locked'?'前置条件未满足':lesson.status==='unknown'?'状态待核实':'可开始'}}{{lesson.duration?' · '+lesson.duration:''}}</text></view><text>›</text></button></view></view></template></view></scroll-view></view></template>
<style scoped>.screen{height:calc(100vh - 92rpx)}.hero{padding:40rpx;border-radius:34rpx;background:linear-gradient(135deg,#152a4c,#3e5c98);color:white}.hero .eyebrow{color:#a8c5ff}.hero-title{display:block;margin:17rpx 0;font-size:43rpx;font-weight:800}.hero-desc{display:block;color:#d2def2;font-size:24rpx;line-height:1.6}.progress{display:flex;justify-content:space-between;margin-top:35rpx;font-size:24rpx}.bar{height:9rpx;margin-top:13rpx;background:#ffffff40;border-radius:99rpx}.bar view{height:100%;background:#adc7ff;border-radius:99rpx}.chapter{padding:15rpx 22rpx}.chapter-head{display:flex;align-items:center;gap:18rpx;width:100%;padding:16rpx 4rpx;background:none;color:#233a5e;text-align:left}.chapter-no{font-size:25rpx;color:#416bd5;font-weight:850}.chapter-title{flex:1;font-size:29rpx;font-weight:800}.lesson{display:flex;align-items:center;gap:16rpx;width:100%;min-height:105rpx;padding:15rpx 5rpx;border-top:1rpx solid #e7edf5;background:white;color:#40526c;text-align:left}.lesson[disabled]{opacity:.62}.state-dot{display:flex;align-items:center;justify-content:center;min-width:48rpx;height:48rpx;border-radius:99rpx;background:#edf2fa;color:#637591;font-size:20rpx}.state-dot.completed{background:#e7f6ed;color:#21814b}.state-dot.current{background:#e8efff;color:#2c5bd0}.state-dot.locked{background:#fff0ed;color:#ab5542}.body{flex:1}.title{display:block;font-size:25rpx;font-weight:750}.meta{display:block;margin-top:5rpx;color:#8795a8;font-size:21rpx}.empty{padding:25rpx;color:#7e8da3;font-size:23rpx}.retry{margin-top:12rpx;color:#2455ca;background:#eef3ff}</style>
