<script setup lang="ts">
import { ref } from "vue";
import { onPullDownRefresh, onShow } from "@dcloudio/uni-app";
import MNavBar from "../../components/MNavBar.vue";
import { statsApi, type Stats, type StatPoint, type HeatDay } from "../../services/resource";
const stats = ref<Stats | null>(null), heat = ref<HeatDay[]>([]), loading = ref(false), error = ref(""), heatError = ref("");
const year = new Date().getFullYear();
const sections: { key: keyof Pick<Stats,"timeTrend"|"reasoning"|"mastery"|"accuracy">; title: string; hint: string }[] = [
  { key: "timeTrend", title: "学习时长趋势", hint: "来自有效学习记录" }, { key: "reasoning", title: "推理能力画像", hint: "按推理步骤类型观察" },
  { key: "mastery", title: "知识掌握", hint: "掌握度由服务端证据更新" }, { key: "accuracy", title: "正确率趋势", hint: "仅展示服务端统计" },
];
function width(points: StatPoint[], value: number) { const max = Math.max(1,...points.map(item => item.value)); return `${Math.max(0,Math.min(100,value/max*100))}%`; }
async function load() { loading.value = true; error.value = ""; heatError.value = ""; try { stats.value = await statsApi.overview(); try { heat.value = await statsApi.heatmap(year); } catch (e) { heat.value = []; heatError.value = e instanceof Error ? e.message : "热力记录暂不可用"; } } catch (e) { stats.value = null; error.value = e instanceof Error ? e.message : "统计暂不可用"; } finally { loading.value = false; } }
onShow(() => { void load(); }); onPullDownRefresh(() => { void load().finally(() => uni.stopPullDownRefresh()); });
</script>
<template><view class="mobile-page stats"><MNavBar title="学习统计" back /><scroll-view scroll-y class="scroll"><view class="page-scroll"><view class="hero"><text class="eyebrow">YOUR LEARNING DATA</text><text class="hero-title">把努力看得更清楚</text><text class="hero-copy">数据来自服务端学习记录。未形成证据的能力维度会保持空白。</text></view>
  <view v-if="loading" class="m-state">正在读取统计…</view><view v-if="error" class="m-state error">{{ error }}<button class="retry" @click="load">重试</button></view>
  <template v-if="stats"><view v-if="stats.metrics.length" class="metric-grid"><view v-for="metric in stats.metrics" :key="metric.label" class="metric"><text class="metric-value">{{ metric.value }}</text><text class="metric-label">{{ metric.label }}</text></view></view><view v-else class="m-state">服务端暂未返回总览指标。</view>
    <view v-for="section in sections" :key="section.key" class="m-card chart"><text class="m-card-title">{{ section.title }}</text><text class="muted">{{ section.hint }}</text><view v-if="!stats[section.key].length" class="empty">暂未形成可展示的数据</view><view v-for="point in stats[section.key]" :key="point.label" class="point"><text class="point-label">{{ point.label }}</text><view class="bar"><view :style="{ width: width(stats[section.key],point.value) }" /></view><text class="point-value">{{ point.value }}</text></view></view>
    <view class="m-card chart"><text class="m-card-title">{{ year }} 学习热力</text><text class="muted">仅按服务端返回的学习日期着色。</text><view v-if="heatError" class="empty">{{ heatError }}</view><view v-else-if="!heat.length" class="empty">服务端尚无热力记录</view><view v-else class="heat-grid"><view v-for="day in heat" :key="day.date" class="heat-cell" :class="day.level > 0 ? 'active' : ''" :style="{ opacity: day.level > 0 ? Math.min(1,.28 + day.level*.12) : .2 }" :aria-label="`${day.date}，强度 ${day.level}`" /></view></view></template>
  </view></scroll-view></view></template>
<style scoped>.stats{display:flex;flex-direction:column;height:100vh}.scroll{flex:1;min-height:0}.hero{padding:35rpx;border-radius:33rpx;background:linear-gradient(140deg,#172b50,#396ba2);color:#fff}.hero .eyebrow{color:#b5d8ff}.hero-title{display:block;font-size:40rpx;font-weight:850}.hero-copy{display:block;margin-top:12rpx;color:#e0eeff;font-size:23rpx;line-height:1.6}.metric-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:15rpx;margin:24rpx 0}.metric{display:flex;flex-direction:column;gap:7rpx;min-height:122rpx;padding:22rpx;border-radius:24rpx;background:#fff}.metric-value{color:#24528d;font-size:37rpx;font-weight:850}.metric-label{color:#687991;font-size:22rpx}.chart{margin-top:21rpx}.chart .muted{display:block;margin-top:9rpx}.empty{padding:30rpx 0;color:#8190a4;font-size:23rpx}.point{display:flex;align-items:center;gap:13rpx;margin-top:18rpx}.point-label{width:118rpx;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#52647e;font-size:21rpx}.bar{flex:1;height:15rpx;border-radius:99rpx;background:#edf1f8}.bar view{height:100%;border-radius:99rpx;background:linear-gradient(90deg,#6e99ed,#68c4b4)}.point-value{width:55rpx;text-align:right;color:#2d527e;font-size:22rpx;font-weight:700}.heat-grid{display:grid;grid-template-columns:repeat(18,1fr);gap:7rpx;margin-top:20rpx}.heat-cell{height:25rpx;border-radius:5rpx;background:#d7e4df}.heat-cell.active{background:#278e72}.retry{display:block;margin-top:12rpx;background:transparent;color:#9e2d44;text-align:left;font-size:23rpx}</style>
