<script setup lang="ts">
import { ref } from "vue";
import { onLoad, onPullDownRefresh, onShow } from "@dcloudio/uni-app";
import MNavBar from "../../components/MNavBar.vue";
import MSheet from "../../components/MSheet.vue";
import { formulaAccessFromMarker, formulaApi, type FormulaDetail } from "../../services/resource";
const id = ref(""), formula = ref<FormulaDetail | null>(null), loading = ref(false), busy = ref(false), error = ref(""), notice = ref(""), drillOpen = ref(false), access = ref<"blocked"|"reference"|"full">("full");
const proofLabel = (status: number | null) => ({ 1: "严格证明", 2: "推导确立", 3: "经验拟合", 4: "尚未证明" })[status as 1] || "证明状态待确认";
async function load() { access.value = formulaAccessFromMarker(); if (access.value === "blocked") { formula.value = null; error.value = "当前受限作答不开放公式详情。交卷后再查看。"; return; } if (!id.value) { error.value = "缺少公式编号"; return; } loading.value = true; error.value = ""; try { formula.value = await formulaApi.detail(id.value, access.value === "full"); } catch (e) { formula.value = null; error.value = e instanceof Error ? e.message : "公式详情暂不可用"; } finally { loading.value = false; } }
async function drill(type: "condition"|"variant"|"apply") { if (access.value !== "full" || busy.value || !formula.value?.drillTypes.includes(type)) return; busy.value = true; error.value = ""; try { const attemptId = await formulaApi.drill(id.value,type); drillOpen.value = false; uni.navigateTo({ url: `/pages/attempt/paper/index?id=${encodeURIComponent(attemptId)}` }); } catch (e) { error.value = e instanceof Error ? e.message : "小练未启动；如请求已发出，请先核对进行中的作答"; } finally { busy.value = false; } }
function copyFormula() { if (!formula.value?.latex) return; uni.setClipboardData({ data: formula.value.latex, success: () => uni.showToast({ title: "已复制表达式", icon: "none" }) }); }
function openDeepdive() { if (formula.value && access.value === "full") uni.navigateTo({ url: `/pages/learn/deepdive/index?type=formula&id=${encodeURIComponent(formula.value.id)}` }); }
function openRelation(id: string) { uni.navigateTo({ url: `/pages/formula/index?id=${encodeURIComponent(id)}` }); }
onLoad(query => { id.value = String(query?.id || ""); }); onShow(() => { void load(); }); onPullDownRefresh(() => { void load().finally(() => uni.stopPullDownRefresh()); });
</script>
<template><view class="mobile-page formula"><MNavBar title="公式详情" back /><scroll-view scroll-y class="scroll"><view class="page-scroll"><view v-if="loading" class="m-state">正在读取公式…</view><view v-if="error" class="m-state error">{{ error }}<button v-if="access!=='blocked'" class="retry" @click="load">重试</button></view><view v-if="notice" class="m-state warning">{{ notice }}</view>
  <template v-if="formula"><view class="formula-hero"><text class="eyebrow">FORMULA · {{ formula.domain || '领域待确认' }}</text><text class="formula-name">{{ formula.name || '公式未命名' }}</text><text class="formula-latex">{{ formula.latex || '表达式尚未发布' }}</text><view class="hero-bottom"><text>{{ proofLabel(formula.proofStatus) }}</text><text>{{ formula.tier === null ? '难度待确认' : `T${formula.tier}` }}</text><button @click="copyFormula">复制</button></view></view>
    <view class="conditions"><text class="condition-title">成立条件 · 使用前先核对</text><text>{{ formula.conditions || '服务端尚未提供完整成立条件，暂勿直接套用。' }}</text></view><view v-if="formula.proofStatus === 4" class="m-state warning">该内容尚未证明，不能当作已确立的定理使用。</view><view v-if="access==='reference'" class="m-state warning">当前作答仅开放公式、符号与条件参考。完整推导、应用和小练请在交卷后查看。</view>
    <view v-if="access==='full'" class="section"><text class="number">01 / 起源</text><text class="section-title-lg">为什么有它</text><text class="section-copy">{{ formula.origin || '已发布内容暂未提供起源说明。' }}</text></view>
    <view class="section"><text class="number">02 / 符号表</text><text class="section-title-lg">每个字母代表什么</text><view v-if="!formula.symbols.length" class="section-empty">符号说明尚未发布。</view><view v-for="symbol in formula.symbols" :key="symbol.symbol" class="symbol-row"><text class="symbol">{{ symbol.symbol }}</text><view><text class="symbol-meaning">{{ symbol.meaning || '含义待补充' }}</text><text v-if="symbol.range" class="range">{{ symbol.range }}</text></view></view></view>
    <template v-if="access==='full'"><view class="section"><text class="number">03 / 完整推导</text><text class="section-title-lg">凭什么成立</text><view v-if="!formula.derivations.length" class="section-empty">该公式推导整理中，或推导摘要暂不可用。</view><view v-for="item in formula.derivations" :key="item.id" class="m-list-row" @click="openDeepdive"><view class="body"><text class="title">{{ item.title }}</text><text class="meta">{{ item.quality || '质量标签待确认' }}</text></view><text class="chevron">›</text></view></view>
      <view class="section"><text class="number">04 / 条件与边界</text><text class="section-title-lg">什么时候不能用</text><text class="section-copy danger-copy">{{ formula.conditions || '完整条件尚未返回，请先核对来源。' }}</text></view>
      <view class="section"><text class="number">05 / 应用</text><text class="section-title-lg">它能解决什么</text><view v-if="!formula.applications.length" class="section-empty">应用说明尚未发布。</view><text v-for="(item,index) in formula.applications" :key="index" class="application">{{ item }}</text></view>
      <view class="section"><text class="number">06 / 家族</text><text class="section-title-lg">连接到哪些公式</text><view v-if="!formula.relations.length" class="section-empty">家族关系尚未发布。</view><view v-for="item in formula.relations" :key="item.id" class="m-list-row" @click="openRelation(item.id)"><view class="body"><text class="title">{{ item.name }}</text><text class="meta">{{ item.type || '关系类型待确认' }}</text></view><text class="chevron">›</text></view></view>
      <view class="section"><text class="number">07 / 变形族</text><text class="section-title-lg">怎么变才不会错</text><view v-if="!formula.legalForms.length && !formula.errorForms.length" class="section-empty">变形示例尚未发布。</view><view v-for="(item,index) in formula.legalForms" :key="`ok-${index}`" class="variant legal"><text>✓ 合法变形</text><text>{{ item }}</text></view><view v-for="(item,index) in formula.errorForms" :key="`err-${index}`" class="variant wrong"><text>✕ 常见错误</text><text>{{ item.formula }}</text><text v-if="item.reason">{{ item.reason }}</text></view></view>
      <button class="m-button drill-button" :disabled="!formula.drillTypes.length" @click="drillOpen=true">{{ formula.drillTypes.length ? '试做一道题' : '小练题型待服务端确认' }}</button></template>
  </template></view></scroll-view><MSheet v-model="drillOpen" title="选择公式小练" height="compact"><view class="drill-options"><button :disabled="!formula?.drillTypes.includes('condition')" @click="drill('condition')">① 条件判断</button><button :disabled="!formula?.drillTypes.includes('variant')" @click="drill('variant')">② 变形识别</button><button :disabled="!formula?.drillTypes.includes('apply')" @click="drill('apply')">③ 应用匹配</button></view><text class="muted">题目和判分来自标准作答接口。缺少题型标记时入口保持关闭。</text></MSheet></view></template>
<style scoped>.formula{display:flex;flex-direction:column;height:100vh}.scroll{flex:1;min-height:0}.formula-hero{padding:35rpx;border-radius:33rpx;background:linear-gradient(145deg,#152b4e,#3d527e);color:#fff}.formula-hero .eyebrow{color:#a9c7ff}.formula-name{display:block;font-size:39rpx;font-weight:850}.formula-latex{display:block;overflow-x:auto;margin:31rpx 0;padding:22rpx 13rpx;border-radius:18rpx;background:#ffffff16;font-family:Georgia,serif;font-size:34rpx;white-space:nowrap}.hero-bottom{display:flex;align-items:center;gap:11rpx;font-size:21rpx}.hero-bottom text{padding:7rpx 12rpx;border:1rpx solid #ffffff55;border-radius:99rpx}.hero-bottom button{margin-left:auto;padding:9rpx 17rpx;border-radius:14rpx;background:#ffffff22;color:#fff;font-size:21rpx}.conditions{display:flex;flex-direction:column;gap:11rpx;margin:20rpx 0;padding:25rpx;border-left:8rpx solid #d44650;border-radius:15rpx;background:#fff0f1;color:#94323d;font-size:24rpx;line-height:1.55;animation:pulse 2.6s ease-in-out infinite}.condition-title{font-weight:850}@keyframes pulse{50%{box-shadow:0 0 0 8rpx #d4465010}}.section{margin:23rpx 0;padding:28rpx;border:1rpx solid #e0e7f1;border-radius:28rpx;background:#fff}.number{color:#4c70b5;font-size:20rpx;font-weight:850;letter-spacing:2rpx}.section-title-lg{display:block;margin:12rpx 0 18rpx;font-size:29rpx;font-weight:850}.section-copy{display:block;white-space:pre-wrap;color:#40536d;font-size:24rpx;line-height:1.75}.danger-copy{color:#a4444d}.section-empty{color:#8896a9;font-size:23rpx;line-height:1.6}.symbol-row{display:flex;gap:20rpx;padding:18rpx 0;border-top:1rpx solid #e9edf3}.symbol{width:90rpx;color:#253f73;font-family:Georgia,serif;font-size:30rpx;font-weight:800}.symbol-meaning{display:block;color:#344961;font-size:24rpx}.range{display:block;margin-top:5rpx;color:#9d434d;font-size:21rpx}.application{display:block;margin-top:10rpx;padding:13rpx 16rpx;border-radius:13rpx;background:#f4f7fb;color:#415774;font-size:24rpx}.variant{display:flex;flex-direction:column;gap:6rpx;margin-top:12rpx;padding:17rpx;border-radius:16rpx;font-size:23rpx}.variant.legal{background:#edf8f0;color:#246c43}.variant.wrong{background:#fff0f0;color:#a33942}.drill-button{margin:25rpx 0}.drill-options{display:flex;flex-direction:column;gap:13rpx;margin-bottom:18rpx}.drill-options button{padding:21rpx;border-radius:17rpx;background:#edf3ff;color:#2855ac;text-align:left;font-size:25rpx;font-weight:750}.retry{display:block;margin-top:12rpx;background:transparent;color:#9e2d44;text-align:left;font-size:23rpx}</style>
