<script setup lang="ts">
import { ref } from "vue";
import { onLoad, onPullDownRefresh } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import MSheet from "../../../components/MSheet.vue";
import { assessmentApi, type Assessment } from "../../../services/pathPlan";
const assessments = ref<Assessment[] | null>(null), selected = ref<Assessment | null>(null), selectedId = ref(""), loading = ref(false), busy = ref(false), error = ref("");
async function load() { loading.value = true; error.value = ""; try { assessments.value = await assessmentApi.catalog(); if (selectedId.value) selected.value = assessments.value.find(a => a.id === selectedId.value) ?? null; } catch (e) { assessments.value = null; error.value = e instanceof Error ? e.message : "测评列表暂不可用"; } finally { loading.value = false; } }
async function start() { if (!selected.value || selected.value.disabled || busy.value) return; busy.value = true; error.value = ""; try { const started = await assessmentApi.start(selected.value.id); selected.value = null; uni.navigateTo({ url: `/pages/attempt/paper/index?id=${encodeURIComponent(started.attemptId)}` }); } catch (e) { error.value = e instanceof Error ? e.message : "测评未启动，请核对状态后再试"; } finally { busy.value = false; } }
onLoad(query => { selectedId.value = String(query?.id || ""); void load(); }); onPullDownRefresh(() => { void load().finally(() => uni.stopPullDownRefresh()); });
</script>
<template><view class="mobile-page assessment"><MNavBar title="起点测评" back /><scroll-view scroll-y class="scroll"><view class="page-scroll"><view class="hero"><text class="eyebrow">ASSESSMENT · FIND YOUR START</text><text class="hero-title">先找到适合自己的起点</text><text class="hero-copy">题目会由服务端自适应安排。测评中关闭 AI、公式与其他辅助，交卷后再看报告。</text></view>
  <view class="notice"><text class="notice-icon">◎</text><view><text class="notice-title">受限作答</text><text class="notice-copy">开始后进入专注作答。测评进度、题目升降档与结束由服务端决定；中途离开可从进行中的作答继续。</text></view></view>
  <view v-if="loading" class="m-state">正在读取可用测评…</view><view v-if="error" class="m-state error">{{ error }}<button class="retry" @click="load">重试</button></view><view v-if="assessments && !assessments.length" class="m-state">目前没有开放的测评。</view>
  <view v-for="item in assessments || []" :key="item.id" class="m-list-row" @click="selected = item"><view class="assessment-icon">◈</view><view class="body"><text class="title">{{ item.title }}</text><text class="meta">{{ item.disabled ? '当前不可开始' : '开始前确认作答规则' }}</text></view><text class="chevron">›</text></view>
  <view class="report-link"><text>已有测评记录？</text><text>报告可从对应作答结果进入；记录编号须由服务端提供。</text></view></view></scroll-view><MSheet :model-value="!!selected" :title="selected?.title || '开始测评'" height="compact" @update:model-value="selected = null"><view class="sheet-copy"><text>测评期间所有辅助入口关闭，答案和解析按服务端权限开放。请预留连续作答时间。</text><text class="muted">如果开考回执缺少受限策略或作答编号，本页不会进入作答。</text></view><template #footer><button class="m-button" :disabled="selected?.disabled || busy" @click="start">{{ busy ? '正在开始…' : '确认并开始测评' }}</button></template></MSheet></view></template>
<style scoped>.assessment{display:flex;flex-direction:column;height:100vh}.scroll{flex:1;min-height:0}.hero{padding:36rpx;border-radius:34rpx;background:linear-gradient(145deg,#20314f,#55569a);color:#fff}.hero .eyebrow{color:#c6c8ff}.hero-title{display:block;font-size:41rpx;font-weight:850;line-height:1.3}.hero-copy{display:block;margin-top:15rpx;color:#e4e7ff;font-size:24rpx;line-height:1.6}.notice{display:flex;gap:19rpx;margin:24rpx 0 31rpx;padding:26rpx;border:1rpx solid #e4d5ab;border-radius:25rpx;background:#fffbec}.notice-icon{font-size:42rpx;color:#986c26}.notice-title{display:block;color:#6e4e1d;font-size:26rpx;font-weight:800}.notice-copy{display:block;margin-top:7rpx;color:#735f3f;font-size:22rpx;line-height:1.55}.assessment-icon{display:flex;align-items:center;justify-content:center;width:66rpx;height:66rpx;border-radius:20rpx;background:#ebeaff;color:#5554a3;font-size:34rpx}.report-link{display:flex;flex-direction:column;gap:7rpx;margin-top:27rpx;color:#687990;font-size:22rpx;line-height:1.5}.sheet-copy{display:flex;flex-direction:column;gap:17rpx;color:#283b56;font-size:25rpx;line-height:1.6}.retry{display:block;margin-top:12rpx;background:transparent;color:#9e2d44;text-align:left;font-size:23rpx}</style>
