<script setup lang="ts">
import { computed, ref } from "vue";
import { onLoad } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import { selectedWrongFor, wrongbook, startRelatedPractice } from "../../../services/attemptApi";
import { mayCountProfile, statusLabel, wrongRows, type WrongRow } from "../../../features/attempt/wrongbookModel";
const qid=ref("");const row=ref<WrongRow|null>(null);const loading=ref(true);const error=ref("");const current=ref(0);const busy=ref(false);const actionError=ref("");
const evidence=computed(()=>row.value?.evidence[current.value]||null);
async function load(){loading.value=true;error.value="";try{let found=selectedWrongFor(qid.value);if(!found){const result=wrongRows(await wrongbook(1,100));found=result?.find(x=>x.questionId===qid.value)||null;}row.value=found;if(!found)error.value="未在当前可读取的错题记录中找到这道题，请返回错题本重试。";}catch(e){error.value=e instanceof Error?e.message:"断链数据暂不可用";}finally{loading.value=false;}}
function toNode(node:number){uni.navigateTo({url:`/pages/learn/node/index?id=${node}`});}
async function practice(){const e=evidence.value;if(!e||!e.warrantNodes.length||!e.remedies.length||busy.value)return;busy.value=true;actionError.value="";try{const attemptId=await startRelatedPractice(e.warrantNodes,Math.min(2,e.remedies.length));uni.navigateTo({url:`/pages/attempt/paper/index?id=${encodeURIComponent(attemptId)}`});}catch(cause){actionError.value=cause instanceof Error?cause.message:"练习未启动";}finally{busy.value=false;}}
onLoad(q=>{qid.value=String(q?.questionId||"");void load();});
</script>
<template><view class="mobile-page"><MNavBar title="断链证据" back/><scroll-view scroll-y class="screen"><view class="page-scroll"><view class="head"><text class="eyebrow">BREAK EVIDENCE</text><text class="page-title">把卡住的位置找清楚</text><text class="muted">建议、观察与自报各有来源；旧链只回放原快照。</text></view>
  <view v-if="loading" class="m-state">正在读取断链证据…</view><view v-else-if="error" class="m-state error">{{error}}<button class="retry" @click="load">重试</button></view>
  <template v-else-if="row"><view class="m-card"><text class="m-card-title">{{row.title}}</text><text class="muted">{{row.nodeName||'关联知识点待补充'}}</text></view>
    <view v-if="!row.evidence.length" class="m-state warning">尚未定位断点。可以从同知识点练习或已发布概念继续学习。</view>
    <template v-else><view v-if="row.evidence.length>1" class="switch"><button v-for="(e,i) in row.evidence" :key="i" :class="{active:current===i}" @click="current=i">证据 {{i+1}}</button></view>
      <view v-if="evidence" class="m-card"><text class="m-chip">{{statusLabel(evidence.status)}}</text><text class="m-card-title evidence-title">{{evidence.status==='suggested'?'可能的断点，尚待确认':evidence.status==='unlocated'?'尚未定位到具体步骤':'原解法中的断点'}}</text><text class="muted">{{mayCountProfile(evidence)?'客观预测观察，可计入推理画像':'不计入客观推理画像'}}</text><view class="meta"><text>来源：{{evidence.source||'未注明'}}</text><text>链版本：{{evidence.chainVersion??'未提供'}}</text><text>原步骤 ID：{{evidence.stepId??'未定位'}}</text><text v-if="evidence.kind">缺口：{{evidence.kind}}</text></view>
        <view v-if="evidence.steps.length" class="chain"><view v-for="step in evidence.steps" :key="step.stepId" :class="{hit:step.stepId===evidence.stepId}"><text class="dot">{{step.stepId}}</text><text>{{step.text||'原步骤说明未保留'}}</text></view></view><view v-else class="m-state">暂无可回放的原解法步骤。不会跳转到新版本的同序号步骤。</view></view>
      <view v-if="evidence" class="m-card"><text class="m-card-title">补哪里</text><text class="muted">有可用资源时才显示入口，训练题以接口返回的实际数量为准。</text><view v-if="evidence.warrantNodes.length" class="nodes"><button v-for="n in evidence.warrantNodes" :key="n" @click="toNode(n)">知识点 #{{n}} →</button></view><text v-if="evidence.remedies.length" class="remedy">当前返回 {{evidence.remedies.length}} 道相关训练题</text><text v-else class="remedy">当前无可用训练题（0 题）；先读已发布概念或稍后复习。</text><view v-for="r in evidence.remedies" :key="r.questionId" class="fallback">{{r.title||'题目 #'+r.questionId}}</view><view v-for="r in evidence.publishedFallback" :key="r.type+r.id" class="fallback">{{r.title}}</view><button v-if="evidence.remedies.length&&evidence.warrantNodes.length" class="m-button" :disabled="busy" @click="practice">{{busy?'启动中…':'开始同知识点练习（目标 '+Math.min(2,evidence.remedies.length)+' 题）'}}</button><view v-if="actionError" class="m-state error">{{actionError}}</view></view>
    </template></template>
</view></scroll-view></view></template>
<style scoped>.screen{height:calc(100vh - 92rpx)}.head{display:flex;flex-direction:column;gap:10rpx;margin:7rpx 0 24rpx}.evidence-title{margin:21rpx 0 7rpx}.meta{display:grid;grid-template-columns:1fr 1fr;gap:12rpx;margin:25rpx 0;padding:20rpx;border-radius:18rpx;background:#f4f7fc;color:#586c88;font-size:22rpx}.chain{display:flex;flex-direction:column;gap:13rpx}.chain view{display:flex;align-items:center;gap:17rpx;padding:17rpx;border-left:5rpx solid #ccd8ed;border-radius:15rpx;background:#f8faff;color:#3c4f6b;font-size:24rpx}.chain view.hit{border-color:#e07353;background:#fff0ed;color:#9f4330}.dot{display:flex;align-items:center;justify-content:center;min-width:49rpx;height:49rpx;border-radius:99rpx;background:#e4ebf8;color:#2755af;font-weight:800}.nodes{display:flex;flex-wrap:wrap;gap:10rpx;margin:20rpx 0}.nodes button,.switch button{padding:12rpx 20rpx;border-radius:99rpx;background:#edf3ff;color:#2556c7;font-size:23rpx}.switch{display:flex;gap:10rpx;margin-bottom:16rpx}.switch button.active{background:#335fd5;color:white}.remedy{display:block;margin:22rpx 0;color:#48617f;font-size:24rpx}.fallback{padding:15rpx;border-radius:13rpx;background:#f4f7fb;color:#3d587a;font-size:23rpx}.retry{margin-top:16rpx;color:#2455c9;background:#eef3ff}</style>
