<script setup lang="ts">
import { computed, ref } from "vue";
import { onLoad, onShow, onHide, onUnload } from "@dcloudio/uni-app";
import { isApiError } from "@learnmath/shared";
import MNavBar from "../../../components/MNavBar.vue";
import { learnApi } from "../../../services/learnApi";
import { lessonOf, readReceipt, readingBlocks, type Lesson, type ReadReceipt } from "../../../features/learn/learnModel";
const id=ref("");const lesson=ref<Lesson|null>(null);const receipt=ref<ReadReceipt|null>(null);const loading=ref(true);const busy=ref(false);const error=ref("");const note=ref("");const heartbeatNote=ref("");
let timer:ReturnType<typeof setInterval>|undefined;let pending=0;let heartBusy=false;
const readDone=computed(()=>receipt.value?.readCompleted===true||lesson.value?.readCompleted===true);
const completeDone=computed(()=>receipt.value?.lessonCompleted===true||lesson.value?.lessonCompleted===true);
const blocks=computed(()=>readingBlocks(lesson.value?.content||""));
function stop(){if(timer)clearInterval(timer);timer=undefined;}
async function heartbeat(){if(heartBusy||pending<=0||!lesson.value)return;heartBusy=true;const seconds=pending;try{await learnApi.heartbeat(id.value,seconds);pending-=seconds;heartbeatNote.value="";}catch(e){heartbeatNote.value="学习时长未同步："+(e instanceof Error?e.message:"网络暂不可用");}finally{heartBusy=false;}}
function start(){stop();if(!lesson.value)return;timer=setInterval(()=>{pending+=30;void heartbeat();},30000);}
async function load(){loading.value=true;error.value="";try{const mapped=lessonOf(await learnApi.lesson(id.value));if(!mapped)throw new Error("课时内容字段尚未对齐或内容为空");lesson.value=mapped;start();}catch(e){lesson.value=null;error.value=e instanceof Error?e.message:"课时暂不可用";}finally{loading.value=false;}}
async function markRead(){if(!lesson.value||busy.value||readDone.value)return;busy.value=true;note.value="";try{const confirmed=readReceipt(await learnApi.read(id.value));if(!confirmed)throw new Error("阅读回执字段不完整，不能确认已读");receipt.value=confirmed;note.value=confirmed.lessonCompleted?"服务端已确认课时完成。":"阅读已记录；课时完成仍由随堂练和服务端策略判定。";}catch(e){note.value="阅读未确认："+(e instanceof Error?e.message:"请求失败");}finally{busy.value=false;}}
async function finish(){if(!lesson.value||busy.value||!readDone.value||completeDone.value)return;busy.value=true;note.value="";try{const confirmed=readReceipt(await learnApi.complete(id.value));if(!confirmed)throw new Error("完成回执字段不完整，暂不能确认完成");receipt.value=confirmed;note.value=confirmed.lessonCompleted?"服务端确认课时完成。奖励与掌握度按独立记录核实。":"当前条件尚未满足；阅读记录与随堂练达标分开计算。";}catch(e){note.value=isApiError(e)&&e.code===3005?"完成条件尚未满足，请先完成随堂客观练习。":"完成未确认："+(e instanceof Error?e.message:"请求失败");}finally{busy.value=false;}}
function toPractice(){uni.switchTab({url:"/pages/practice/index"});}
onLoad(q=>{id.value=String(q?.id||"");void load();});onShow(()=>{if(lesson.value)start();});onHide(()=>{stop();void heartbeat();});onUnload(()=>{stop();void heartbeat();});
</script>
<template><view class="mobile-page"><MNavBar title="专注课时" back/><scroll-view scroll-y class="screen"><view class="page-scroll"><view v-if="loading" class="m-state">正在读取课时内容…</view><view v-else-if="!lesson" class="m-state error">{{error||'课时暂不可用'}}<button class="retry" @click="load">重试</button></view><template v-else><view class="head"><text class="eyebrow">LESSON · 先理解，再确认</text><text class="page-title">{{lesson.title}}</text><text class="muted">阅读确认、练习达标和课时完成分别记录。</text></view>
  <view class="status"><view><text class="status-dot" :class="{done:readDone}"/>阅读 {{readDone?'已确认':'未确认'}}</view><view><text class="status-dot" :class="{done:receipt?.practicePassed===true||lesson.practicePassed===true}"/>练习 {{receipt?.practicePassed===true||lesson.practicePassed===true?'已达标':'待达标'}}</view><view><text class="status-dot" :class="{done:completeDone}"/>课时 {{completeDone?'已完成':'进行中'}}</view></view>
  <view class="m-card content"><text class="eyebrow">READING · 学习正文</text><view class="body"><template v-for="(block,i) in blocks" :key="i"><text v-if="block.kind!=='image'" class="block" :class="[block.kind,'level-'+(block.level||0)]">{{block.kind==='list'?'•  ':''}}{{block.text}}</text><image v-else :src="block.src" :alt="block.text" mode="widthFix" class="reading-image" /></template></view></view><view v-if="lesson.videoUrl" class="m-card"><text class="m-card-title">配套视频</text><video :src="lesson.videoUrl" controls class="video" /></view>
  <view class="m-card policy"><text class="m-card-title">完成条件</text><text v-if="lesson.completionPolicy==='read_only'">本课为明确发布的纯阅读课；阅读确认后可请求完成。</text><text v-else-if="lesson.completionPolicy==='practice_required'">默认随堂练门槛：客观题全部提交且正确率至少 80%。具体结果由服务端判定。</text><text v-else>课时完成策略尚未由服务端明确返回；只能等待完成接口核实。</text><button v-if="lesson.completionPolicy==='practice_required'" class="m-button secondary" @click="toPractice">前往练习中心</button></view>
  <view v-if="heartbeatNote" class="m-state warning">{{heartbeatNote}}</view><view v-if="note" class="m-state" :class="{success:completeDone}">{{note}}</view>
  <view class="actions"><button class="m-button secondary" :disabled="readDone||busy" @click="markRead">{{readDone?'阅读已记录':'确认已阅读'}}</button><button class="m-button" :disabled="!readDone||completeDone||busy" @click="finish">{{completeDone?'课时已完成':'请求完成课时'}}</button></view>
</template></view></scroll-view></view></template>
<style scoped>.screen{height:calc(100vh - 92rpx)}.page-scroll{padding-bottom:110rpx}.head{display:flex;flex-direction:column;gap:13rpx;padding:22rpx 0 30rpx}.status{display:flex;justify-content:space-between;gap:5rpx;margin-bottom:22rpx;color:#536985;font-size:20rpx}.status view{display:flex;align-items:center;gap:5rpx}.status-dot{width:14rpx;height:14rpx;border-radius:99rpx;background:#c3ccda}.status-dot.done{background:#2eb36b}.content{padding:36rpx}.body{display:block;line-height:1.9;color:#25364e;font-size:28rpx;margin-top:20rpx}.block{display:block;white-space:pre-wrap;margin:18rpx 0;line-height:1.85}.block.heading{margin:29rpx 0 13rpx;color:#17365e;font-weight:850}.block.level-1{font-size:37rpx}.block.level-2{font-size:33rpx}.block.level-3,.block.level-4{font-size:29rpx}.block.list{margin:8rpx 0;padding-left:17rpx}.block.quote{padding:14rpx 19rpx;border-left:5rpx solid #6f90dc;background:#f3f6fc;color:#486180}.block.math{overflow-wrap:anywhere;padding:22rpx;border-radius:18rpx;background:#f0f4fb;color:#274e8e;text-align:center;font-family:Georgia,serif}.block.code{padding:21rpx;border-radius:17rpx;background:#172a46;color:#eaf2ff;font-family:monospace;font-size:23rpx;line-height:1.6}.reading-image{width:100%;margin:20rpx 0;border-radius:15rpx}.video{width:100%;height:380rpx;margin-top:20rpx;border-radius:17rpx}.policy text:not(.m-card-title){display:block;margin:18rpx 0;color:#536781;font-size:24rpx;line-height:1.7}.actions{display:flex;gap:13rpx;margin-top:28rpx}.actions button{flex:1;font-size:23rpx}.retry{margin-top:13rpx;color:#2455c8;background:#edf3ff}</style>
