<script setup lang="ts">
import { computed, ref } from "vue";
import { onLoad } from "@dcloudio/uni-app";
import MNavBar from "../../../components/MNavBar.vue";
import { masterWrong, redoWrongbook, selectWrong, wrongbook } from "../../../services/attemptApi";
import { dueLabel, statusLabel, wrongRows, type WrongRow } from "../../../features/attempt/wrongbookModel";
const rows=ref<WrongRow[]>([]);const loading=ref(true);const busy=ref(false);const error=ref("");const tab=ref<"all"|"due"|"unmastered"|"break">("all");
const filtered=computed(()=>rows.value.filter(r=>tab.value==="all"||tab.value==="due"&&r.dueDays!==null&&r.dueDays<=0&&!r.mastered||tab.value==="unmastered"&&!r.mastered||tab.value==="break"&&r.evidence.length>0));
async function load(){loading.value=true;error.value="";try{const result=wrongRows(await wrongbook(1,40));if(!result)throw new Error("错题数据格式尚未对齐");rows.value=result;}catch(e){rows.value=[];error.value=e instanceof Error?e.message:"错题本暂不可用";}finally{loading.value=false;}}
function toBreak(row:WrongRow){selectWrong(row);uni.navigateTo({url:`/pages/attempt/break/index?questionId=${encodeURIComponent(row.questionId)}`});}
async function redo(){const count=filtered.value.filter(r=>!r.mastered).length;if(!count||busy.value)return;busy.value=true;error.value="";try{const id=await redoWrongbook(count);uni.navigateTo({url:`/pages/attempt/paper/index?id=${encodeURIComponent(id)}`});}catch(e){error.value=e instanceof Error?e.message:"重练未启动";}finally{busy.value=false;}}
async function master(row:WrongRow){if(busy.value)return;busy.value=true;error.value="";try{await masterWrong(row.questionId);await load();}catch(e){error.value=e instanceof Error?e.message:"标记未保存";}finally{busy.value=false;}}
onLoad(()=>{void load();});
</script>
<template><view class="mobile-page"><MNavBar title="错题本" back/><scroll-view scroll-y class="screen"><view class="page-scroll"><view class="intro"><text class="eyebrow">REVIEW · 复习证据</text><text class="page-title">从错因，走向下一步</text><text class="muted">断链状态只反映已保存的观察、自报或建议。</text></view>
  <view class="tabs"><button v-for="t in [{k:'all',v:'全部'},{k:'due',v:'到期'},{k:'unmastered',v:'待巩固'},{k:'break',v:'有断链'}] as const" :key="t.k" :class="{active:tab===t.k}" @click="tab=t.k">{{t.v}}</button></view>
  <view v-if="loading" class="m-state">正在读取错题…</view><view v-else-if="error" class="m-state error">{{error}}<button class="retry" @click="load">重试</button></view><view v-else-if="!filtered.length" class="m-state">当前筛选下暂无错题记录。</view>
  <view v-for="row in filtered" :key="row.questionId" class="m-card wrong"><view class="row-top"><text class="m-chip">{{dueLabel(row.dueDays)}}</text><text class="muted">{{row.nodeName||'知识点待补充'}}</text></view><text class="m-card-title">{{row.title}}</text><text v-if="row.wrongCount!==null" class="muted">累计错答 {{row.wrongCount}} 次</text><view class="badges"><text v-for="(e,i) in row.evidence" :key="i" class="badge" :class="e.status">{{statusLabel(e.status)}}</text><text v-if="!row.evidence.length" class="badge">尚无断链证据</text></view><view class="actions"><button @click="toBreak(row)">看断链证据</button><button v-if="!row.mastered" :disabled="busy" @click="master(row)">标记掌握</button></view></view>
  <view v-if="rows.length" class="m-sticky-actions"><button class="m-button" :disabled="!filtered.some(r=>!r.mastered)||busy" @click="redo">重练本页待巩固错题（{{filtered.filter(r=>!r.mastered).length}}）</button></view>
</view></scroll-view></view></template>
<style scoped>.screen{height:calc(100vh - 92rpx)}.page-scroll{padding-bottom:180rpx}.intro{display:flex;flex-direction:column;gap:9rpx;margin:9rpx 0 26rpx}.tabs{display:flex;gap:9rpx;overflow:auto;margin-bottom:24rpx}.tabs button{flex:none;min-height:69rpx;padding:10rpx 21rpx;border-radius:99rpx;background:white;border:1rpx solid #dbe5f4;color:#63738d;font-size:23rpx}.tabs button.active{background:#2f60df;color:white;border-color:#2f60df}.row-top{display:flex;justify-content:space-between;align-items:center;margin-bottom:15rpx}.wrong .m-card-title{margin-bottom:10rpx}.badges{display:flex;flex-wrap:wrap;gap:8rpx;margin:22rpx 0}.badge{padding:8rpx 14rpx;border-radius:99rpx;background:#eef1f6;color:#60718a;font-size:21rpx}.badge.suggested{background:#fff5dc;color:#9b620a}.badge.observed{background:#fff0ed;color:#ab4939}.badge.self_reported{background:#edf2ff;color:#315ac5}.actions{display:flex;gap:10rpx}.actions button{flex:1;min-height:72rpx;border-radius:16rpx;background:#edf3ff;color:#2558cf;font-size:23rpx;font-weight:750}.actions button[disabled]{opacity:.5}.retry{margin-top:15rpx;color:#2455ca;background:#eef3ff}</style>
