<script setup lang="ts">
import { ref } from "vue";
import { onPullDownRefresh, onShow } from "@dcloudio/uni-app";
import MNavBar from "../../components/MNavBar.vue";
import { statsApi, type WeeklyReport } from "../../services/resource";
const report = ref<WeeklyReport | null>(null), loading = ref(false), error = ref("");
async function load() { loading.value = true; error.value = ""; try { report.value = await statsApi.latest(); } catch (e) { report.value = null; error.value = e instanceof Error ? e.message : "周报暂不可用"; } finally { loading.value = false; } }
onShow(() => { void load(); }); onPullDownRefresh(() => { void load().finally(() => uni.stopPullDownRefresh()); });
</script>
<template><view class="mobile-page weekly"><MNavBar title="学习周报" back /><scroll-view scroll-y class="scroll"><view class="page-scroll"><view class="cover"><text class="eyebrow">WEEKLY LEARNING REVIEW</text><text class="cover-title">{{ report?.title || '这一周，值得回望' }}</text><text class="cover-period">{{ report?.period || '报告周期以服务端记录为准' }}</text><view class="cover-rule" /></view>
  <view v-if="loading" class="m-state">正在读取最新报告…</view><view v-if="error" class="m-state error">{{ error }}<button class="retry" @click="load">重试</button></view><view v-if="!loading && !report && !error" class="m-state">尚无可用周报。完成学习后可再查看。</view>
  <template v-if="report"><view class="metric-list"><view v-for="metric in report.metrics" :key="metric.label" class="metric"><text class="number">{{ metric.value }}</text><text class="caption">{{ metric.label }}</text></view></view><view v-if="!report.metrics.length" class="m-state">本期报告没有返回数字摘要。</view>
    <view class="paper-section"><text class="section-kicker">01 / 本周观察</text><text class="section-title-lg">这周的学习记录</text><text class="paper-copy">{{ report.commentary || '本期点评暂未由服务端提供。' }}</text></view><view class="paper-section"><text class="section-kicker">02 / 下一步</text><text class="section-title-lg">下周可以这样继续</text><view v-if="!report.suggestions.length" class="paper-copy">暂无服务端建议。</view><view v-for="(suggestion,index) in report.suggestions" :key="index" class="suggestion"><text class="suggestion-number">{{ String(index+1).padStart(2,'0') }}</text><text>{{ suggestion }}</text></view></view>
    <view class="share-note"><text>分享海报</text><text>海报绘图结构尚未在接口契约中定义，当前不生成未经核对的学习成绩图。</text></view><button class="m-button secondary" disabled>生成分享海报 · 暂不可用</button></template>
  </view></scroll-view></view></template>
<style scoped>.weekly{display:flex;flex-direction:column;height:100vh}.scroll{flex:1;min-height:0}.cover{padding:43rpx 36rpx 25rpx;border-radius:33rpx;background:#152b46;color:#fff}.cover .eyebrow{color:#9ac7e1}.cover-title{display:block;margin:27rpx 0 20rpx;font-size:44rpx;font-weight:850;line-height:1.3}.cover-period{display:block;color:#cbdcec;font-size:23rpx}.cover-rule{width:65rpx;height:5rpx;margin-top:30rpx;background:#f1bb76}.metric-list{display:grid;grid-template-columns:repeat(2,1fr);gap:14rpx;margin:23rpx 0}.metric{display:flex;flex-direction:column;gap:6rpx;padding:22rpx;border-radius:22rpx;background:#fff}.number{color:#203d6a;font-size:39rpx;font-weight:850}.caption{color:#738096;font-size:21rpx}.paper-section{margin:27rpx 0;padding:28rpx;border-radius:27rpx;background:#fff}.section-kicker{color:#ad7b42;font-size:20rpx;font-weight:800;letter-spacing:2rpx}.section-title-lg{display:block;margin:15rpx 0 20rpx;color:#213651;font-size:30rpx;font-weight:800}.paper-copy{display:block;color:#4d6079;font-size:25rpx;line-height:1.8;white-space:pre-wrap}.suggestion{display:flex;gap:15rpx;padding:14rpx 0;border-top:1rpx solid #e9edf3;color:#344b68;font-size:24rpx;line-height:1.6}.suggestion-number{color:#bd8c58;font-weight:800}.share-note{display:flex;flex-direction:column;gap:8rpx;margin:30rpx 0 15rpx;color:#687990;font-size:22rpx;line-height:1.6}.share-note text:first-child{color:#203b60;font-size:26rpx;font-weight:800}.retry{display:block;margin-top:12rpx;background:transparent;color:#9e2d44;text-align:left;font-size:23rpx}</style>
