<script setup lang="ts">
import { computed, ref } from "vue";
import { onLoad } from "@dcloudio/uni-app";
import { isApiError } from "@learnmath/shared";
import MNavBar from "../../../components/MNavBar.vue";
import { attemptId, learnApi } from "../../../services/learnApi";
import { cardTabs, narrativeOf, nodeOf, nodeStatus, type CardKey, type GraphNode, type Narrative } from "../../../features/learn/learnModel";
const id=ref(0);const node=ref<GraphNode|null>(null);const narrative=ref<Narrative|null>(null);const loading=ref(true);const error=ref("");const narrativeError=ref("");const tab=ref<CardKey>("origin");const busy=ref(false);const note=ref("");
const status=computed(()=>node.value?nodeStatus(node.value):"未知");const canPractice=computed(()=>node.value?.locked===false&&node.value?.preparing===false);
async function load(){loading.value=true;error.value="";narrativeError.value="";try{const [n,c]=await Promise.allSettled([learnApi.node(id.value),learnApi.narrative(id.value)]);if(n.status==="rejected")throw n.reason;node.value=nodeOf(n.value);if(!node.value)throw new Error("知识点字段尚未对齐");if(c.status==="fulfilled")narrative.value=narrativeOf(c.value);else narrativeError.value=c.reason instanceof Error?c.reason.message:"概念卡暂不可用";}catch(e){node.value=null;error.value=e instanceof Error?e.message:"知识点暂不可用";}finally{loading.value=false;}}
async function practice(){if(!canPractice.value||busy.value)return;busy.value=true;note.value="";try{const result=attemptId(await learnApi.startPractice(id.value));if(!result)throw new Error("服务端未返回作答编号");uni.navigateTo({url:`/pages/attempt/paper/index?id=${encodeURIComponent(result)}`});}catch(e){note.value=isApiError(e)&&e.code===3311?"前置未达标，服务端拒绝开始练习。":e instanceof Error?e.message:"练习未启动";}finally{busy.value=false;}}
onLoad(q=>{id.value=Number(q?.id);if(!Number.isSafeInteger(id.value)||id.value<=0){error.value="知识点编号无效";loading.value=false;return;}void load();});
</script>
<template><view class="mobile-page"><MNavBar title="知识点详情" back/><scroll-view scroll-y class="screen"><view class="page-scroll"><view v-if="loading" class="m-state">正在读取知识点和已发布概念卡…</view><view v-else-if="!node" class="m-state error">{{error||'知识点暂不可用'}}<button class="retry" @click="load">重试</button></view><template v-else><view class="hero"><text class="eyebrow">KNOWLEDGE NODE · #{{node.id}}</text><text class="page-title">{{node.name}}</text><text>{{node.description||'定义与说明待补全'}}</text><view class="score"><strong>{{node.score!==null&&node.insufficientSample===false?node.score+'%':'—'}}</strong><text>{{status}}</text></view></view>
  <view class="section-title">概念四卡 <text class="muted">{{narrative?'已发布 v'+narrative.version:'暂无发布快照'}}</text></view><view class="tabs"><button v-for="t in cardTabs" :key="t.key" :class="{active:tab===t.key}" @click="tab=t.key">{{t.label}}</button></view><view class="m-card card"><text class="m-card-title">{{cardTabs.find(t=>t.key===tab)?.label}}</text><text class="story">{{narrative?.cards[tab]||'待补全'}}</text><text v-if="narrative?.missing.length" class="muted">待补全：{{narrative.missing.join('、')}}</text><text v-if="narrativeError" class="muted">概念卡读取失败：{{narrativeError}}</text><text v-if="!narrative" class="muted">只展示已发布快照；工作稿不可见。</text></view>
  <view class="m-card"><text class="m-card-title">能力与前置</text><text class="muted">{{status}}。掌握度由服务端有效客观作答证据计算。</text><view v-if="node.locked===true" class="m-state warning">前置尚未达标，练习入口暂不可用。</view><view v-else-if="node.locked===null||node.preparing===null" class="m-state warning">前置或发布状态未确认，暂不开放练习。</view></view><view class="m-card"><text class="m-card-title">代表题与关联内容</text><text class="muted">当前接口未返回可核实的代表题、课时和公式关联，不跳转到固定资源。</text></view><view v-if="note" class="m-state warning">{{note}}</view><button class="m-button practice" :disabled="!canPractice||busy" @click="practice">{{busy?'启动中…':'从此处开始练习'}}</button>
</template></view></scroll-view></view></template>
<style scoped>.screen{height:calc(100vh - 92rpx)}.page-scroll{padding-bottom:120rpx}.hero{display:flex;flex-direction:column;gap:13rpx;padding:34rpx;border-radius:33rpx;background:linear-gradient(145deg,#142748,#2c4e89);color:white}.hero .eyebrow{color:#a4c1fb}.hero .page-title{color:white}.hero>text:not(.page-title):not(.eyebrow){color:#c6d4ea;font-size:24rpx;line-height:1.6}.score{display:flex;align-items:center;gap:20rpx;margin-top:14rpx;padding:17rpx;border:1rpx solid #ffffff36;border-radius:18rpx;background:#ffffff13}.score strong{font-size:40rpx}.score text{font-size:23rpx}.tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:5rpx;margin-bottom:15rpx}.tabs button{min-height:70rpx;padding:5rpx;background:#edf2f9;color:#657794;border-radius:14rpx;font-size:21rpx}.tabs button.active{background:#315dd1;color:white;font-weight:800}.card{min-height:260rpx}.story{display:block;white-space:pre-wrap;margin:28rpx 0;color:#263951;font-size:27rpx;line-height:1.8}.practice{margin:24rpx 0}.retry{margin-top:15rpx;color:#2454cc;background:#eef3ff}</style>
